steps:
  # Step 1: Install dependencies
  - id: npm-ci
  - name: 'gcr.io/cloud-builders/npm'
    args: ['ci']

  # Step 2: Run tests (TDD step)
  - id: npm-test
  - name: 'gcr.io/cloud-builders/npm'
    args: ['test', '--', '--ci', '--watchAll=false']
    waitFor: ["npm-ci"]

  # Step 3: Build app
  - id: npm-build
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
    waitFor: ["npm-test"]

  # Step 4: Sync to GCS bucket (only changed files)
  - id: sync-to-gcs
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: ['gsutil', '-m', 'rsync', '-r', '-c', 'build/', 'gs://manage.cocreatestartup.com']
    waitFor: ["npm-build"]

  # Step 5: Invalidate CDN cache
  - id: invalidate-cdn
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: ['gcloud', 'compute', 'url-maps', 'invalidate-cdn-cache', 'cocreate-map', '--path "/index.html"']
    waitFor: ["sync-to-gcs"]

timeout: "600s"

options:
  logging: CLOUD_LOGGING_ONLY